<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_sex</name>
   <tag></tag>
   <elementGuidId>0b8e5f47-0bf0-4126-b4b1-931bdc40c69c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='choice']/descendant::h4[contains(text(),'${sex}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='choice']/descendant::h4[contains(text(),'${sex}')]</value>
   </webElementProperties>
</WebElementEntity>
