<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>test_other</name>
   <tag></tag>
   <elementGuidId>b74b2f2b-fbb8-4874-ba97-10f7421c5315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='append_text_wrapper']/descendant::textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='append_text_wrapper']/descendant::textarea</value>
   </webElementProperties>
</WebElementEntity>
