<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_area3</name>
   <tag></tag>
   <elementGuidId>a9d49780-8445-4739-84ae-ba12645b0cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='page_body']/descendant::input[@type='text'][${text}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='page_body']/descendant::input[@type='text'][${text}]</value>
   </webElementProperties>
</WebElementEntity>
